# Config file for automatic testing at travis-ci.org
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: python setup.py test
# deploy automatically to pypi when a release is made
deploy:
  provider: pypi
  user: nlesc
  password:
    secure: FIXME; see README for more info
  on:
    tags: true
    branch: master
