name: Anaconda Publish

on:
  release:
    types: [published]

jobs:

  publish:
    name: ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-build
          auto-activate-base: false
          auto-update-conda: true
          environment-file: conda/environment-build.yml
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload no
          export BUILD_FOLDER=/tmp/matchms/_build
          mkdir -p $BUILD_FOLDER
          conda build --numpy 1.18.1 --no-include-recipe \
            --channel bioconda --channel conda-forge \
            --croot $BUILD_FOLDER \
            ./conda
      - name: Push the package to anaconda cloud
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER=/tmp/matchms/_build
          anaconda --token ${{ secrets.ANACONDA_TOKEN }} upload --user nlesc --force $BUILD_FOLDER/noarch/*.tar.bz2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-test
          auto-activate-base: false
          auto-update-conda: true
          channels: conda-forge,bioconda,nlesc
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Install the conda package from anaconda repository
        shell: bash -l {0}
        run: |
          conda install -c bioconda -c conda-forge -c nlesc matchms
      - name: Install development dependencies
        shell: bash -l {0}
        run: python -m pip install -r conda/requirements-dev.txt
      - name: Test the installed conda package
        shell: bash -l {0}
        run: |
          cd ${CONDA_PREFIX}/pkgs/matchms-*/site-packages/tests
          pytest --ignore-glob='test_version_string_consistency.py'
